export const FETCH_DAYS_START = 'FETCH_DAYS'
export const FETCH_DAYS_SUCCESS = 'FETCH_DAYS_SUCCESS'
export const FETCH_DAYS_ERROR = 'FETCH_DAYS_ERROR'
export const GET_TOTAL_ALL_DAYS = 'GET_TOTAL_ALL_DAYS'
export const REFRESH_ALL_DAYS = 'REFRESH_ALL_DAYS'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const GET_USER_KEY = 'GET_USER_KEY'

export const CREATE_WASTE_ITEM = 'CREATE_WASTE_ITEM'

export const GET_USER_COMPONENT = 'GET_USER_COMPONENT'
export const NEW_MONEY_MOVE = 'NEW_MONEY_MOVE'
export const SET_CURRENT_DATA = 'SET_CURRENT_DATA'
export const SET_TOTAL_BALANCE = 'SET_TOTAL_BALANCE'
export const CHANGE_VALID_VALUE = 'CHANGE_VALID_VALUE'
export const INVALID_VALUE = 'INVALID_VALUE'
export const DELETE_ITEM = 'DELETE_ITEM'

export const DEFAULT = 'DEFAULT'

